# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1190, 666)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 750, 650))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 748, 648))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.DataTable = QtWidgets.QTableWidget(Form)
        self.DataTable.setGeometry(QtCore.QRect(930, 10, 250, 650))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataTable.sizePolicy().hasHeightForWidth())
        self.DataTable.setSizePolicy(sizePolicy)
        self.DataTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DataTable.setRowCount(20)
        self.DataTable.setObjectName("DataTable")
        self.DataTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.DataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.DataTable.setHorizontalHeaderItem(1, item)
        self.DataTable.horizontalHeader().setCascadingSectionResizes(False)
        self.DataTable.horizontalHeader().setDefaultSectionSize(150)
        self.DataTable.horizontalHeader().setMinimumSectionSize(50)
        self.DataTable.horizontalHeader().setStretchLastSection(True)
        self.DataTable.verticalHeader().setDefaultSectionSize(25)
        self.AddUnitPButt = QtWidgets.QPushButton(Form)
        self.AddUnitPButt.setGeometry(QtCore.QRect(770, 10, 150, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddUnitPButt.sizePolicy().hasHeightForWidth())
        self.AddUnitPButt.setSizePolicy(sizePolicy)
        self.AddUnitPButt.setObjectName("AddUnitPButt")
        self.DltUnitPButt = QtWidgets.QPushButton(Form)
        self.DltUnitPButt.setGeometry(QtCore.QRect(770, 40, 90, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DltUnitPButt.sizePolicy().hasHeightForWidth())
        self.DltUnitPButt.setSizePolicy(sizePolicy)
        self.DltUnitPButt.setObjectName("DltUnitPButt")
        self.LoadCfgPButt = QtWidgets.QPushButton(Form)
        self.LoadCfgPButt.setGeometry(QtCore.QRect(770, 130, 150, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadCfgPButt.sizePolicy().hasHeightForWidth())
        self.LoadCfgPButt.setSizePolicy(sizePolicy)
        self.LoadCfgPButt.setObjectName("LoadCfgPButt")
        self.DltUnitNumSBox = QtWidgets.QSpinBox(Form)
        self.DltUnitNumSBox.setGeometry(QtCore.QRect(870, 40, 50, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DltUnitNumSBox.sizePolicy().hasHeightForWidth())
        self.DltUnitNumSBox.setSizePolicy(sizePolicy)
        self.DltUnitNumSBox.setObjectName("DltUnitNumSBox")
        self.SaveCfgPButt = QtWidgets.QPushButton(Form)
        self.SaveCfgPButt.setGeometry(QtCore.QRect(770, 160, 150, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveCfgPButt.sizePolicy().hasHeightForWidth())
        self.SaveCfgPButt.setSizePolicy(sizePolicy)
        self.SaveCfgPButt.setObjectName("SaveCfgPButt")
        self.DltAllUnitsPButt = QtWidgets.QPushButton(Form)
        self.DltAllUnitsPButt.setGeometry(QtCore.QRect(770, 70, 150, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DltAllUnitsPButt.sizePolicy().hasHeightForWidth())
        self.DltAllUnitsPButt.setSizePolicy(sizePolicy)
        self.DltAllUnitsPButt.setObjectName("DltAllUnitsPButt")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(770, 100, 150, 25))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Клиент TA1-USB"))
        item = self.DataTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Имя"))
        item = self.DataTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Значение"))
        self.AddUnitPButt.setText(_translate("Form", "Добавить"))
        self.DltUnitPButt.setText(_translate("Form", "Удалить"))
        self.LoadCfgPButt.setText(_translate("Form", "Загрузить"))
        self.SaveCfgPButt.setText(_translate("Form", "Сохранить"))
        self.DltAllUnitsPButt.setText(_translate("Form", "Удалить все"))

